# See: https://docs.travis-ci.com/user/languages/rust/

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - libdbus-1-dev
      - shellcheck

cache: cargo

# Clippy and rustfmt are available as of Rust 1.31/2018. See:
# https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html#new-tools
before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - scripts/travis-checks.sh
