[package]
name = "killjoy"
version = "0.1.0"
authors = ["Jeremy Audet <jerebear@protonmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
dbus = "0.6"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
textwrap = {version="0", features = ["term_size"]}
xdg = "2"
