# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
authors = ["Jeremy Audet <jerebear@protonmail.com>"]
categories = ["command-line-utilities"]
description = "Monitor systemd units."
edition = "2018"
keywords = ["d-bus", "dbus", "systemd", "unit"]
license = "GPL-3.0-or-later"
name = "killjoy"
readme = "README.md"
repository = "https://github.com/Ichimonji10/killjoy"
version = "0.1.0"

[dependencies]
clap = "2"
dbus = "0.6"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
textwrap = "0"
xdg = "2"

[dev-dependencies]
assert_cmd = "0.11"
tempfile = "3.1"

[badges]
travis-ci = {repository = "Ichimonji10/killjoy"}
